import { useRef, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { importLocalFonts } from "@/lib/api/fonts";
import type { ApiResult } from "@/types/result";

type LocalFile = File & { path?: string };

export function ImportFontsDialog({ compact = false }: { compact?: boolean }) {
  const queryClient = useQueryClient(); const picker = useRef<HTMLInputElement>(null); const [open, setOpen] = useState(false); const [files, setFiles] = useState<LocalFile[]>([]); const [dragging, setDragging] = useState(false);
  const mutation = useMutation({ mutationFn: async () => unwrap(await importLocalFonts({ paths: files.map((file) => file.path ?? file.name), scope: "user" })), onSuccess: (result) => { setOpen(false); setFiles([]); queryClient.invalidateQueries({ queryKey: ["installed-fonts"] }); toast.success(`${result.length} font file${result.length === 1 ? "" : "s"} imported.`); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Import failed. Use desktop file paths."), });
  const accept = (next: FileList | null) => setFiles((current) => [...current, ...Array.from(next ?? []).filter((file) => /\.(ttf|otf)$/i.test(file.name)) as LocalFile[]]);
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size={compact ? "sm" : "default"} variant={compact ? "ghost" : "outline"}>Import{compact ? "" : " fonts"}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Import local fonts</DialogTitle><DialogDescription>Original files stay where they are. Fontsequal copies valid TTF/OTF files into its managed user library.</DialogDescription></DialogHeader><input ref={picker} className="hidden" accept=".ttf,.otf" multiple type="file" onChange={(event) => accept(event.target.files)} /><button className={`grid min-h-32 w-full place-items-center rounded-md border border-dashed p-5 text-center text-sm ${dragging ? "border-primary bg-selected text-foreground" : "border-border bg-muted/40 text-muted-foreground"}`} type="button" onClick={() => picker.current?.click()} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); accept(event.dataTransfer.files); }}>Drop .ttf or .otf files here, or choose files</button>{files.length ? <div className="max-h-44 space-y-2 overflow-y-auto">{files.map((file, index) => <div key={`${file.name}-${index}`} className="rounded-md border bg-muted/40 px-3 py-2 text-sm"><p className="text-foreground">{file.name}</p><p className="mt-1 text-xs text-muted-foreground">{Math.ceil(file.size / 1024)} KB · {file.type || "Font file"}</p></div>)}</div> : null}<DialogFooter><Button variant="outline" onClick={() => setFiles([])}>Clear</Button><Button disabled={!files.length || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Importing" : `Import ${files.length || ""}`}</Button></DialogFooter></DialogContent></Dialog>;
}
function unwrap<T>(result: ApiResult<T>): T { if (result.ok) return result.data; throw new Error(result.error); }
