import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PageContainer } from "@/app/PageContainer";
import { useTheme } from "@/app/theme-provider";
import { refreshGoogleFontsCache } from "@/lib/api/google-fonts";
import { scanSystemFonts } from "@/lib/api/fonts";
import { getSettings, updateSettings } from "@/lib/api/settings";
import type { ApiResult } from "@/types/result";
import type { UpdateSettingsInput } from "@/types/settings";

type ThemeMode = "light" | "dark" | "system";

export function SettingsPage() {
  const queryClient = useQueryClient(); const { setTheme } = useTheme(); const [danger, setDanger] = useState<"cache" | "data" | null>(null);
  const settings = useQuery({ queryKey: ["settings"], queryFn: async () => unwrap(await getSettings()) });
  const save = useMutation({ mutationFn: async (input: UpdateSettingsInput) => unwrap(await updateSettings(input)), onSuccess: (next) => { queryClient.setQueryData(["settings"], next); toast.success("Settings saved locally."); }, onError: () => toast.error("Could not save settings.") });
  const rescan = useMutation({ mutationFn: async () => unwrap(await scanSystemFonts()), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["installed-fonts"] }); toast.success("Font scan complete."); } });
  const refresh = useMutation({ mutationFn: async () => unwrap(await refreshGoogleFontsCache()), onSuccess: () => toast.success("Google Fonts cache refreshed."), onError: () => toast.error("Google Fonts connection failed.") });
  const current = settings.data; const patch = (input: UpdateSettingsInput) => save.mutate(input);
  const changeTheme = (theme: ThemeMode) => { setTheme(theme); patch({ theme }); };

  return <PageContainer className="max-w-6xl px-4 py-4 lg:px-6"><section className="space-y-3"><header className="glass-panel px-4 py-3"><h2 className="text-sm font-semibold">Settings</h2><p className="mt-1 text-xs text-muted-foreground">Local preferences and library behavior</p></header><div className="grid gap-3 lg:grid-cols-[176px_minmax(0,1fr)]"><aside className="glass-panel h-fit p-2"><SettingsNav /></aside><div className="space-y-3">
    <Section id="appearance" title="Appearance" description="Preview defaults and color mode."><Row label="Theme" help="System follows desktop preference."><ThemeSegmented value={current?.theme ?? "dark"} onChange={changeTheme} /></Row><Row label="Default preview text"><Input defaultValue={current?.previewText} onBlur={(event) => patch({ previewText: event.target.value })} /></Row><Row label="Preview density"><Select value={current?.previewDensity ?? "comfortable"} onValueChange={(previewDensity) => patch({ previewDensity: previewDensity as "compact" | "comfortable" | "spacious" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="compact">Compact</SelectItem><SelectItem value="comfortable">Comfortable</SelectItem><SelectItem value="spacious">Spacious</SelectItem></SelectContent></Select></Row></Section>
    <Section id="library" title="Font management" description="User-only managed font library."><Row label="Managed font directory" help="~/.local/share/fonts/fontsequal on Linux."><Button size="sm" variant="raised" onClick={() => toast.message("Managed directory opens through desktop shell in production.")}>Open directory</Button></Row><Row label="Rescan local fonts"><Button disabled={rescan.isPending} size="sm" variant="raised" onClick={() => rescan.mutate()}>{rescan.isPending ? "Scanning" : "Rescan fonts"}</Button></Row><Row label="Refresh font cache"><Button size="sm" variant="toolbar" onClick={() => rescan.mutate()}>Refresh cache</Button></Row></Section>
    <Section id="providers" title="Google Fonts" description="Key remains in local SQLite settings."><Row label="API key"><Input defaultValue={current?.googleFontsApiKey} placeholder="AIza…" type="password" onBlur={(event) => patch({ googleFontsApiKey: event.target.value })} /></Row><Row label="Connection and cache" help={current?.updatedAt ? `Last local update: ${current.updatedAt}` : "Not synced yet."}><Button disabled={refresh.isPending} size="sm" variant="raised" onClick={() => refresh.mutate()}>{refresh.isPending ? "Testing" : "Test and refresh"}</Button></Row></Section>
    <Section id="data" title="Data" description="Database stays local."><Row label="Database path" help="Fontsequal application data directory."><Button size="sm" variant="toolbar" onClick={() => toast.message("Local JSON export available through desktop file picker.")}>Export JSON</Button></Row><Row label="Import local JSON"><Button size="sm" variant="toolbar" onClick={() => toast.message("Choose a Fontsequal JSON export to import.")}>Import JSON</Button></Row><Row label="Reset Google Fonts cache"><Button size="sm" variant="destructive" onClick={() => setDanger("cache")}>Reset cache</Button></Row><Row label="Reset all app data" help="Does not delete system fonts."><Button size="sm" variant="destructive" onClick={() => setDanger("data")}>Reset all data</Button></Row></Section>
  </div></div><Dialog open={Boolean(danger)} onOpenChange={(open) => !open && setDanger(null)}><DialogContent><DialogHeader><DialogTitle>{danger === "data" ? "Reset all local app data?" : "Reset Google Fonts cache?"}</DialogTitle><DialogDescription>{danger === "data" ? "This action is destructive. Managed files and system fonts are not removed by this dialog." : "Cached Google Fonts metadata will be removed."}</DialogDescription></DialogHeader><DialogFooter><Button variant="glass" onClick={() => setDanger(null)}>Cancel</Button><Button variant="destructive" onClick={() => { toast.message("Reset command requires desktop data migration support."); setDanger(null); }}>Confirm reset</Button></DialogFooter></DialogContent></Dialog></section></PageContainer>;
}

function SettingsNav() { return <nav className="space-y-1 text-sm" aria-label="Settings sections">{[["appearance", "Appearance"], ["library", "Font management"], ["providers", "Google Fonts"], ["data", "Data"]].map(([id, label]) => <a key={id} className="block rounded-[9px] px-2.5 py-2 text-muted-foreground transition-colors hover:bg-[var(--control-hover)] hover:text-foreground" href={`#${id}`}>{label}</a>)}</nav>; }
function ThemeSegmented({ value, onChange }: { value: ThemeMode; onChange: (theme: ThemeMode) => void }) { return <div className="glass-control inline-flex p-0.5">{(["light", "dark", "system"] as ThemeMode[]).map((theme) => <Button key={theme} aria-pressed={value === theme} className={value === theme ? "selected-surface h-7 px-2.5" : "h-7 px-2.5"} size="sm" variant="segmented" onClick={() => onChange(theme)}>{theme[0]!.toUpperCase() + theme.slice(1)}</Button>)}</div>; }
function Section({ id, title, description, children }: { id: string; title: string; description: string; children: React.ReactNode }) { return <section id={id} className="glass-panel scroll-mt-4 p-4"><div className="mb-2"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{description}</p></div><div>{children}</div></section>; }
function Row({ label, help, children }: { label: string; help?: string; children: React.ReactNode }) { return <div className="grid gap-3 border-t border-[var(--border-soft)] py-3 first:border-t-0 first:pt-1 md:grid-cols-[1fr_260px] md:items-center"><div><p className="text-sm font-medium">{label}</p>{help ? <p className="mt-1 text-xs text-muted-foreground">{help}</p> : null}</div><div>{children}</div></div>; }
function unwrap<T>(result: ApiResult<T>): T { if (result.ok) return result.data; throw new Error(result.error); }
