import type { FontFamily } from "@/types/font";

export const mockBrowseFonts: FontFamily[] = [
  {
    id: "inter",
    family: "Inter",
    category: "sans-serif",
    source: "google",
    variants: [
      { id: "regular", label: "Regular", weight: 400, style: "normal" },
      { id: "medium", label: "Medium", weight: 500, style: "normal" },
      { id: "bold", label: "Bold", weight: 700, style: "normal" },
    ],
    files: [],
    metadata: {
      foundry: "Rasmus Andersson",
      license: "OFL",
      lastModified: "2026-07-07T00:00:00Z",
      languages: ["latin", "latin-ext"],
    },
    subsets: ["latin", "latin-ext"],
    isFavorite: true,
    isInstalled: true,
  },
  {
    id: "fraunces",
    family: "Fraunces",
    category: "serif",
    source: "google",
    variants: [
      { id: "regular", label: "Regular", weight: 400, style: "normal" },
      { id: "italic", label: "Italic", weight: 400, style: "italic" },
      { id: "bold", label: "Bold", weight: 700, style: "normal" },
    ],
    files: [],
    metadata: {
      foundry: "Undercase Type",
      license: "OFL",
      lastModified: "2026-07-07T00:00:00Z",
      languages: ["latin"],
    },
    subsets: ["latin"],
    isFavorite: false,
    isInstalled: false,
  },
  {
    id: "space-grotesk",
    family: "Space Grotesk",
    category: "sans-serif",
    source: "google",
    variants: [
      {
        id: "variable",
        label: "Variable",
        weight: 400,
        style: "normal",
        variableAxes: { wght: 700 },
      },
    ],
    files: [],
    metadata: {
      foundry: "Florian Karsten",
      license: "OFL",
      lastModified: "2026-07-07T00:00:00Z",
      languages: ["latin", "vietnamese"],
    },
    subsets: ["latin", "vietnamese"],
    isFavorite: false,
    isInstalled: false,
  },
  {
    id: "jetbrains-mono",
    family: "JetBrains Mono",
    category: "monospace",
    source: "google",
    variants: [
      { id: "regular", label: "Regular", weight: 400, style: "normal" },
      { id: "bold", label: "Bold", weight: 700, style: "normal" },
    ],
    files: [],
    metadata: {
      foundry: "JetBrains",
      license: "OFL",
      lastModified: "2026-07-07T00:00:00Z",
      languages: ["latin", "cyrillic"],
    },
    subsets: ["latin", "cyrillic"],
    isFavorite: true,
    isInstalled: false,
  },
  {
    id: "dm-serif-display",
    family: "DM Serif Display",
    category: "display",
    source: "google",
    variants: [
      { id: "regular", label: "Regular", weight: 400, style: "normal" },
      { id: "italic", label: "Italic", weight: 400, style: "italic" },
    ],
    files: [],
    metadata: {
      foundry: "Colophon Foundry",
      license: "OFL",
      lastModified: "2026-07-06T00:00:00Z",
      languages: ["latin", "latin-ext"],
    },
    subsets: ["latin", "latin-ext"],
    isFavorite: false,
    isInstalled: false,
  },
  {
    id: "caveat",
    family: "Caveat",
    category: "handwriting",
    source: "google",
    variants: [
      {
        id: "variable",
        label: "Variable",
        weight: 400,
        style: "normal",
        variableAxes: { wght: 700 },
      },
    ],
    files: [],
    metadata: {
      foundry: "Impallari Type",
      license: "OFL",
      lastModified: "2026-07-05T00:00:00Z",
      languages: ["latin", "cyrillic"],
    },
    subsets: ["latin", "cyrillic"],
    isFavorite: false,
    isInstalled: false,
  },
  {
    id: "bodoni-moda",
    family: "Bodoni Moda",
    category: "serif",
    source: "google",
    variants: [
      {
        id: "variable",
        label: "Variable",
        weight: 400,
        style: "normal",
        variableAxes: { wght: 900, opsz: 96 },
      },
      { id: "italic", label: "Italic", weight: 400, style: "italic" },
    ],
    files: [],
    metadata: {
      foundry: "Indestructible Type",
      license: "OFL",
      lastModified: "2026-07-04T00:00:00Z",
      languages: ["latin", "latin-ext", "vietnamese"],
    },
    subsets: ["latin", "latin-ext", "vietnamese"],
    isFavorite: true,
    isInstalled: false,
  },
  {
    id: "manrope",
    family: "Manrope",
    category: "sans-serif",
    source: "google",
    variants: [
      {
        id: "variable",
        label: "Variable",
        weight: 400,
        style: "normal",
        variableAxes: { wght: 800 },
      },
    ],
    files: [],
    metadata: {
      foundry: "Mikhail Sharanda",
      license: "OFL",
      lastModified: "2026-07-03T00:00:00Z",
      languages: ["latin", "cyrillic"],
    },
    subsets: ["latin", "cyrillic"],
    isFavorite: false,
    isInstalled: true,
  },
];
